server:
  port: 8083

spring:
  application:
    name: Community Domain Server
  r2dbc:
    url: r2dbc:pool:mysql://coinbuying.c5sgvczuoq5f.us-west-1.rds.amazonaws.com/community
    username: admin
    password: coin1234
    #initialization-mode: always
    port: 3306

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG

msa:
  client:
    url:
      gateway: http://localhost:8000

