DROP TABLE IF EXISTS post;

CREATE TABLE IF NOT EXISTS post (
    post_id INT(20) AUTO_INCREMENT PRIMARY KEY NOT NULL COMMENT '게시글ID',
    board_type VARCHAR(50) NOT NULL COMMENT '게시판타입',
    post_type VARCHAR(50) NOT NULL COMMENT '게시글타입',
    title VARCHAR(50) NOT NULL COMMENT '타이틀',
    contents VARCHAR(2000) NOT NULL COMMENT '컨텐츠',
    writer VARCHAR(50) NOT NULL COMMENT '작성자',
    counter INT(20) NOT NULL COMMENT '조회수',
    show_yn VARCHAR(1) NOT NULL COMMENT '숨김여부',
    create_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일',
    update_dt DATETIME ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);